/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'clawgrep.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./clawgrep.darwin-x64.node')
          } else {
            nativeBinding = require('clawgrep-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'clawgrep.darwin-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./clawgrep.darwin-arm64.node')
          } else {
            nativeBinding = require('clawgrep-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'clawgrep.win32-x64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./clawgrep.win32-x64-msvc.node')
          } else {
            nativeBinding = require('clawgrep-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          throw new Error(
            'Unsupported libc: musl is not supported on x64. Use a glibc-based Linux distribution.',
          )
        } else {
          localFileExisted = existsSync(join(__dirname, 'clawgrep.linux-x64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./clawgrep.linux-x64-gnu.node')
            } else {
              nativeBinding = require('clawgrep-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          throw new Error(
            'Unsupported libc: musl is not supported on arm64. Use a glibc-based Linux distribution.',
          )
        } else {
          localFileExisted = existsSync(join(__dirname, 'clawgrep.linux-arm64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./clawgrep.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('clawgrep-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error('Failed to load native binding')
}

const { search } = nativeBinding

module.exports.search = search
