/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single search result returned to JavaScript. */
export interface JsSearchResult {
  /** File path containing the match. */
  file: string
  /** 1-based start line of the match. */
  lineNum: number
  /** End line of the match. */
  endLine: number
  /** The matched text. */
  text: string
  /** Combined relevance score (higher = more relevant). */
  score: number
  /** Semantic component of the score. */
  semanticScore: number
  /** Keyword component of the score. */
  keywordScore: number
}
/** Options for the search function. */
export interface JsSearchOptions {
  /** Number of results to return (default: 5). */
  topK?: number
  /** Minimum combined score cutoff (0.0–1.0). */
  minScore?: number
  /** Weight for semantic similarity (default: 0.7). */
  semanticWeight?: number
  /** Weight for keyword matching (default: 0.3). */
  keywordWeight?: number
  /** Boost factor for file/folder path matches (default: 1.0). */
  pathBoost?: number
  /** Force re-embed all files. */
  reindex?: boolean
  /** Don't read or write caches. */
  noCache?: boolean
  /** Custom cache directory. */
  cacheDir?: string
  /** Do not respect .gitignore files. */
  noGitignore?: boolean
}
/**
 * Search files by meaning and keywords.
 *
 * `query` — natural language or keyword search string.
 * `paths` — array of file or directory paths to search.
 * `options` — optional search configuration.
 */
export declare function search(query: string, paths: Array<string>, options?: JsSearchOptions | undefined | null): Array<JsSearchResult>
